name: "Block Message Commits"
description: "Prevent merging pull requests that contain commit messages"
author: "xt0rted"
branding:
  icon: "alert-circle"
  color: "Red"

inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  
  mesaje-block:
    description: "Mensaje que se buscara en los commit para bloquear"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
